---
- name: Install packages
  become: true
  apt:
    name:
      - nginx
    state: present

- name: Make directories
  file:
    dest: "{{ item }}"
    state: directory
    mode: u=rwx
  with_items:
    - /home/pi/mainsail
    - /home/pi/mainsail_backup

- name: Copy over nginx conf
  become: true
  template:
    src: mainsail.conf
    dest: /etc/nginx/sites-enabled/default
    mode: u=rw

- name: Backup Mainsail
  copy:
    src: /home/pi/mainsail/
    dest: /home/pi/mainsail_backup/
    remote_src: true

- name: Fetch Mainsail
  unarchive:
    src: https://github.com/mainsail-crew/mainsail/releases/latest/download/mainsail.zip
    dest: /home/pi/mainsail
    remote_src: true

- name: Generate client auth
  include_tasks: client_certs.yml
  vars:
    client_certs_dir: "/etc/nginx/mainsail"
    client_certs_host: "{{ ansible_host }}"
    client_certs_force: false
    client_certs_country: FI
    client_certs_organization: Me
    client_certs_domains_san:
      - "{{ ansible_host }}"

- name: Restart and enable service
  become: true
  service:
    name: nginx
    state: restarted
    enabled: true

- name: Wait for successful start
  wait_for:
    port: 443
    host: localhost

- name: Remove Mainsail Backup
  file:
    path: /home/pi/mainsail_backup/
    state: absent
