---
- name: Install nginx
  apt:
    name:
      - nginx
    state: present

- name: Make directories
  file:
    dest: "{{ item }}"
    state: directory
    mode: u=rwx
  with_items:
    - /home/pi/mainsail

- name: Copy over nginx conf
  become: true
  copy:
    src: mainsail.conf
    dest: /etc/nginx/sites-enabled/default
    mode: u=rw

- name: Fetch Mainsail
  unarchive:
    src: https://github.com/meteyou/mainsail/releases/latest/download/mainsail.zip
    dest: /home/pi/mainsail
    remote_src: true

- name: Add users
  become: true
  htpasswd:
    path: /etc/nginx/mainsail.passwd
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    owner: root
    group: www-data
    mode: 0640
  with_items: "{{ printer_users }}"
  loop_control:
    label: "{{ item.username }}"

- name: Restart and enable service
  become: true
  service:
    name: nginx
    state: restarted
    enabled: true

- name: Wait for successful start
  wait_for:
    port: 80
    host: localhost
