---
- name: Update package cache
  become: true
  apt:
    update_cache: true

- name: Upgrade packages
  become: true
  apt:
    upgrade: safe

- name: Ensure packages are installed
  become: true
  apt:
    name:
      - git
      - dfu-util
      - unzip
      - python3
    state: present
